# Generated by Django 5.1.1 on 2024-12-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_job_file_upload_job_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
